apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gitea-db-network-policy
  namespace: cronohub
spec:
  podSelector:
    matchLabels:
      app: gitea-db
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: gitea
      ports:
        - protocol: TCP
          port: 5432
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: gitea
      ports:
        - protocol: TCP
          port: 5432