apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: cronohub
  name: do-storage-gitea-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: do-block-storage