{{- if .Values.krok_db.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.krok_db.name }}-pvc
spec:
  accessModes:
    - {{ .Values.krok_db.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.krok_db.persistence.storage }}
  storageClassName: {{ .Values.krok_db.persistence.storageClassName }}
{{- end }}