apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.server.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.global.server.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.global.server.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.server.name }}
    spec:
      containers:
        - name: {{ .Values.image.name }}
          image: {{ .Values.image.image }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.image.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.image.containerPort }}
            initialDelaySeconds: 15
            periodSeconds: 20
          ports:
            - containerPort: {{ .Values.image.containerPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secret.name }}
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secret.name }}
                  key: password
          args:
            {{-  range .Values.image.args }}
            - {{ . }}
            {{- end }}
            - --db-password=$(POSTGRES_PASSWORD)
            - --db-username=$(POSTGRES_USER)
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - mountPath: /tmp/krok
              subPath: krok # important so it gets mounted correctly instead of adding a lost-and-found folder.
              name: data
          {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.global.server.name }}-pvc
      {{- end }}