// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	oauth2 "golang.org/x/oauth2"
)

// OAuthAuthenticator is an autogenerated mock type for the OAuthAuthenticator type
type OAuthAuthenticator struct {
	mock.Mock
}

// Exchange provides a mock function with given fields: ctx, code
func (_m *OAuthAuthenticator) Exchange(ctx context.Context, code string) (*oauth2.Token, error) {
	ret := _m.Called(ctx, code)

	var r0 *oauth2.Token
	if rf, ok := ret.Get(0).(func(context.Context, string) *oauth2.Token); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth2.Token)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GenerateState provides a mock function with given fields: redirectURL
func (_m *OAuthAuthenticator) GenerateState(redirectURL string) (string, error) {
	ret := _m.Called(redirectURL)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(redirectURL)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(redirectURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAuthCodeURL provides a mock function with given fields: state
func (_m *OAuthAuthenticator) GetAuthCodeURL(state string) string {
	ret := _m.Called(state)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(state)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// VerifyState provides a mock function with given fields: rawToken
func (_m *OAuthAuthenticator) VerifyState(rawToken string) (string, error) {
	ret := _m.Called(rawToken)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(rawToken)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(rawToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
