// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	providers "github.com/krok-o/krok/pkg/krok/providers"
	mock "github.com/stretchr/testify/mock"
)

// UserCache is an autogenerated mock type for the UserCache type
type UserCache struct {
	mock.Mock
}

// Add provides a mock function with given fields: email, id
func (_m *UserCache) Add(email string, id int) {
	_m.Called(email, id)
}

// ClearTTL provides a mock function with given fields:
func (_m *UserCache) ClearTTL() {
	_m.Called()
}

// Has provides a mock function with given fields: email
func (_m *UserCache) Has(email string) (*providers.UserCacheItem, bool) {
	ret := _m.Called(email)

	var r0 *providers.UserCacheItem
	if rf, ok := ret.Get(0).(func(string) *providers.UserCacheItem); ok {
		r0 = rf(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*providers.UserCacheItem)
		}
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// Remove provides a mock function with given fields: email
func (_m *UserCache) Remove(email string) {
	_m.Called(email)
}
