// Code generated by mockery v2.6.0. DO NOT EDIT.

package mocks

import (
	providers "github.com/krok-o/krok/pkg/krok/providers"
	mock "github.com/stretchr/testify/mock"
)

// Email is an autogenerated mock type for the Email type
type Email struct {
	mock.Mock
}

// Notify provides a mock function with given fields: email, event, payload
func (_m *Email) Notify(email string, event providers.Event, payload providers.Payload) error {
	ret := _m.Called(email, event, payload)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, providers.Event, providers.Payload) error); ok {
		r0 = rf(email, event, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
