// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// SupportedPlatformListHandler is an autogenerated mock type for the SupportedPlatformListHandler type
type SupportedPlatformListHandler struct {
	mock.Mock
}

// ListSupportedPlatforms provides a mock function with given fields:
func (_m *SupportedPlatformListHandler) ListSupportedPlatforms() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}
