// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Hooks is an autogenerated mock type for the Hooks type
type Hooks struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, raw, opts
func (_m *Hooks) Execute(ctx context.Context, raw string, opts ...interface{}) (string, bool, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, raw)
	_ca = append(_ca, opts...)
	ret := _m.Called(_ca...)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) string); ok {
		r0 = rf(ctx, raw, opts...)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(context.Context, string, ...interface{}) bool); ok {
		r1 = rf(ctx, raw, opts...)
	} else {
		r1 = ret.Get(1).(bool)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, string, ...interface{}) error); ok {
		r2 = rf(ctx, raw, opts...)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
