// Code generated by mockery v2.6.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Loader is an autogenerated mock type for the Loader type
type Loader struct {
	mock.Mock
}

// Load provides a mock function with given fields: ctx, location
func (_m *Loader) Load(ctx context.Context, location string) (func(string, []interface{}) (string, bool, error), error) {
	ret := _m.Called(ctx, location)

	var r0 func(string, []interface{}) (string, bool, error)
	if rf, ok := ret.Get(0).(func(context.Context, string) func(string, []interface{}) (string, bool, error)); ok {
		r0 = rf(ctx, location)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func(string, []interface{}) (string, bool, error))
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, location)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Watch provides a mock function with given fields: ctx
func (_m *Loader) Watch(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
