// Code generated by mockery v2.6.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PlatformTokenProvider is an autogenerated mock type for the PlatformTokenProvider type
type PlatformTokenProvider struct {
	mock.Mock
}

// GetTokenForPlatform provides a mock function with given fields: vcs
func (_m *PlatformTokenProvider) GetTokenForPlatform(vcs int) (string, error) {
	ret := _m.Called(vcs)

	var r0 string
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(vcs)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(vcs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveTokenForPlatform provides a mock function with given fields: token, vcs
func (_m *PlatformTokenProvider) SaveTokenForPlatform(token string, vcs int) error {
	ret := _m.Called(token, vcs)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int) error); ok {
		r0 = rf(token, vcs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
