// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// Tar is an autogenerated mock type for the Tar type
type Tar struct {
	mock.Mock
}

// Untar provides a mock function with given fields: dst, reader
func (_m *Tar) Untar(dst string, reader io.Reader) error {
	ret := _m.Called(dst, reader)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, io.Reader) error); ok {
		r0 = rf(dst, reader)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
