// Code generated by mockery v2.6.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Watcher is an autogenerated mock type for the Watcher type
type Watcher struct {
	mock.Mock
}

// Run provides a mock function with given fields: ctx
func (_m *Watcher) Run(ctx context.Context) {
	_m.Called(ctx)
}
