// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.0
// source: krok.proto

package protos

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HandleHooksRequest contains information to handle hook requests
type HandleHooksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rid int64 `protobuf:"varint,1,opt,name=rid,proto3" json:"rid,omitempty"`
	Vid int64 `protobuf:"varint,2,opt,name=vid,proto3" json:"vid,omitempty"`
}

func (x *HandleHooksRequest) Reset() {
	*x = HandleHooksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_krok_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandleHooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleHooksRequest) ProtoMessage() {}

func (x *HandleHooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_krok_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleHooksRequest.ProtoReflect.Descriptor instead.
func (*HandleHooksRequest) Descriptor() ([]byte, []int) {
	return file_krok_proto_rawDescGZIP(), []int{0}
}

func (x *HandleHooksRequest) GetRid() int64 {
	if x != nil {
		return x.Rid
	}
	return 0
}

func (x *HandleHooksRequest) GetVid() int64 {
	if x != nil {
		return x.Vid
	}
	return 0
}

// HandleHooksResponse contains information of the response from handle hooks
type HandleHooksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HandleHooksResponse) Reset() {
	*x = HandleHooksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_krok_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandleHooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleHooksResponse) ProtoMessage() {}

func (x *HandleHooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_krok_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleHooksResponse.ProtoReflect.Descriptor instead.
func (*HandleHooksResponse) Descriptor() ([]byte, []int) {
	return file_krok_proto_rawDescGZIP(), []int{1}
}

var File_krok_proto protoreflect.FileDescriptor

var file_krok_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6b, 0x72, 0x6f, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6b, 0x72,
	0x6f, 0x6b, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x38, 0x0a, 0x12, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x48, 0x6f, 0x6f,
	0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x72, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x76,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x76, 0x69, 0x64, 0x22, 0x15, 0x0a,
	0x13, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x48, 0x6f, 0x6f, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x32, 0x81, 0x01, 0x0a, 0x0b, 0x4b, 0x72, 0x6f, 0x6b, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x72, 0x0a, 0x0b, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x48, 0x6f,
	0x6f, 0x6b, 0x73, 0x12, 0x1b, 0x2e, 0x6b, 0x72, 0x6f, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x61,
	0x6e, 0x64, 0x6c, 0x65, 0x48, 0x6f, 0x6f, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1c, 0x2e, 0x6b, 0x72, 0x6f, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x48, 0x6f, 0x6f, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x28,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x22, 0x22, 0x1d, 0x2f, 0x76, 0x31, 0x2f, 0x6b, 0x72, 0x6f, 0x6b,
	0x2f, 0x7b, 0x72, 0x69, 0x64, 0x7d, 0x2f, 0x7b, 0x76, 0x69, 0x64, 0x7d, 0x2f, 0x63, 0x61, 0x6c,
	0x6c, 0x62, 0x61, 0x63, 0x6b, 0x3a, 0x01, 0x2a, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x72, 0x6f, 0x6b, 0x2d, 0x6f, 0x2f, 0x6b, 0x72,
	0x6f, 0x6b, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_krok_proto_rawDescOnce sync.Once
	file_krok_proto_rawDescData = file_krok_proto_rawDesc
)

func file_krok_proto_rawDescGZIP() []byte {
	file_krok_proto_rawDescOnce.Do(func() {
		file_krok_proto_rawDescData = protoimpl.X.CompressGZIP(file_krok_proto_rawDescData)
	})
	return file_krok_proto_rawDescData
}

var file_krok_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_krok_proto_goTypes = []interface{}{
	(*HandleHooksRequest)(nil),  // 0: krok.v1.HandleHooksRequest
	(*HandleHooksResponse)(nil), // 1: krok.v1.HandleHooksResponse
}
var file_krok_proto_depIdxs = []int32{
	0, // 0: krok.v1.KrokService.HandleHooks:input_type -> krok.v1.HandleHooksRequest
	1, // 1: krok.v1.KrokService.HandleHooks:output_type -> krok.v1.HandleHooksResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_krok_proto_init() }
func file_krok_proto_init() {
	if File_krok_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_krok_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandleHooksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_krok_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandleHooksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_krok_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_krok_proto_goTypes,
		DependencyIndexes: file_krok_proto_depIdxs,
		MessageInfos:      file_krok_proto_msgTypes,
	}.Build()
	File_krok_proto = out.File
	file_krok_proto_rawDesc = nil
	file_krok_proto_goTypes = nil
	file_krok_proto_depIdxs = nil
}
