create table commands (
    id serial primary key ,
    name varchar unique not null,
    schedule varchar,
    filename varchar unique not null,
    hash varchar unique not null,
    location varchar unique not null,
    enabled boolean not null
);

create table repositories (
    id serial primary key,
    name varchar ( 256 ) unique not null,
    url varchar ( 256 )
);

create table rel_command_repositories (
    id serial primary key,
    repository_id int not null,
    command_id int unique not null
);

create table rel_repositories_command (
    id serial primary key,
    command_id int not null,
    repository_id int unique not null
);

create table users (
    id serial primary key,
    -- email is coming from openid registration.
    email varchar(256) unique not null,
    last_login date,
    display_name varchar(50)
);

-- api keys will be generated by the user.
create table apikeys (
    id serial primary key,
    name varchar,
    api_key_id varchar unique not null,
    -- this will be shown once then never again as it will be stored encrypted.
    api_key_secret varchar not null,
    user_id int not null,
    ttl date
);

-- The files lock which will contain the lock for a file with a timestamp of creation.
-- Locks that are older than 10 minutes will be purged.
create table file_lock (
    name varchar ( 256 ) unique not null,
    lock_start date
)
