package models

import (
	"time"
)

// ApiKey is an api key pair generated by the user to access the api without the frontend.
type ApiKey struct {
	Name string    `json:"name,omitempty"`
	Key  string    `json:"key"`
	ID   string    `json:"id"`
	TTL  time.Time `json:"ttl"`
}
