package models

import (
	"time"
)

// ApiKey is an api key pair generated by the user to access the api without the frontend.
type ApiKey struct {
	Name         string    `json:"name,omitempty"`
	ApiKeyID     string    `json:"api_key_id"`
	ApiKeySecret string    `json:"api_key_secret"`
	TTL          time.Time `json:"ttl"`
}
