apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.krok_server.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.krok_server.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.krok_server.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.krok_server.name }}
    spec:
      containers:
        - name: {{ .Values.krok_server.image.name }}
          image: {{ .Values.krok_server.image.image }}
          ports:
            - containerPort: {{ .Values.krok_server.image.containerPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          args:
            {{-  range .Values.krok_server.image.args }}
            - {{ . }}
            {{- end }}