name: Create release
on:
  push:
    tags:
      - 'v*'
env:
  ORG: krokhook
  IMAGE: krok
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        id: prep
        run: |
          VERSION=sha-${GITHUB_SHA::8}
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF/refs\/tags\//}
          fi
          echo ::set-output name=BUILD_DATE::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          echo ::set-output name=VERSION::${VERSION}
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: "--debug"
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: krokhook
          password: ${{ secrets.DOCKERHUB_PASSWORD_KROKHOOK }}
      - name: Publish multi-arch container image
        uses: docker/build-push-action@v2
        with:
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
            docker.io/${{ env.ORG }}/${{ env.IMAGE }}:${{ steps.prep.outputs.VERSION }}
            docker.io/${{ env.ORG }}/${{ env.IMAGE }}:latest
          labels: |
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ steps.prep.outputs.VERSION }}
            org.opencontainers.image.created=${{ steps.prep.outputs.BUILD_DATE }}
      - name: Check images
        run: |
          docker buildx imagetools inspect docker.io/${{ env.ORG }}/${{ env.IMAGE }}:${{ steps.prep.outputs.VERSION }}
          docker pull docker.io/${{ env.ORG }}/${{ env.IMAGE }}:${{ steps.prep.outputs.VERSION }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --release-notes=docs/release_notes/${{ steps.prep.outputs.VERSION }}.md --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
